apiVersion: v1
kind: Service
metadata:
  namespace: mydev-ywyi
  name: saga-orchestrators-service
spec:
  selector:
    app: saga-orchestrators
  ports:
  - protocol: TCP
    name: saga-orchestrators
    port: 8080
    targetPort: 8080
  - protocol: TCP
    name: saga-orchestrators-mgmt
    port: 8081
    targetPort: 8081
