apiVersion: v1
kind: Service
metadata:
  namespace: mydev-ywyi
  name: saga-ticket-consumers-service
spec:
  selector:
    app: saga-ticket-consumers
  ports:
  - protocol: TCP
    name: saga-ticket-consumers
    port: 8080
    targetPort: 8080
  - protocol: TCP
    name: saga-ticket-consumers-mgmt
    port: 8081
    targetPort: 8081
