apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mydev-ywyi
  name: cqrs-consumer-streams-deploy
  labels:
    app: cqrs-consumer-streams
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cqrs-consumer-streams
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8081'
        prometheus.io/path: '/actuator/prometheus'
      labels:
        app: cqrs-consumer-streams
    spec:
      containers:
      - name: cqrs-consumer-streams
        image: eks-dev-zdb-registry.cloudzcp.io/mydev-ywyi/cqrs-consumer-streams:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 8081
        volumeMounts:
          - name: cqrs-consumer-streams-config
            mountPath: "/config"
            readOnly: true
      imagePullSecrets:
        - name: harbor-registry-secret
      volumes:
        - name: cqrs-consumer-streams-config
          configMap:
            name: cqrs-consumer-streams-config
            items:
              - key: "application.yaml"
                path: "application.yaml"
              - key: "logback.xml"
                path: "logback.xml"
