apiVersion: v1
kind: Service
metadata:
  namespace: mydev-ywyi
  name: cqrs-consumer-streams-service
spec:
  selector:
    app: cqrs-consumer-streams
  ports:
  - protocol: TCP
    name: cqrs-consumer-streams
    port: 8080
    targetPort: 8080
  - protocol: TCP
    name: cqrs-consumer-streams-mgmt
    port: 8081
    targetPort: 8081
