spring:
  profiles:
    active: dev
  application:
    name: saga-orchestrator
  kafka:
    bootstrap-servers: http://mydev-db-mytest-kafka.mydev-db:9092
      #consumer:
      #key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      #value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    #properties.schema.registry.url: http://localhost:9999

server:
  port: 8080

logging:
  level:
    root: INFO
    cnadata: DEBUG

logging.config: file:/config/logback.xml

spring.main.allow-bean-definition-overriding: true

--- #dev 환경
spring:
  datasource:
    url: jdbc:mariadb://a77af7a1caaaf4d84a206b39779ef098-c3ca47260c19debc.elb.ap-northeast-2.amazonaws.com/mydev-db?allowMultiQueries=true
    username: admin
    password: ywyi1004
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      idle-timeout: 300
      max-lifetime: 300
  jpa:
    open-in-view: true
    generate-ddl: true
    show-sql: true
    hibernate:
      #ddl-auto: create
      ddl-auto: update
      #ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        #physical-strategy: cnadata.outbox.util.DBLowerCaseNamingStrategy
        #physical-strategy: cnadata.outbox.util.DBUpperCaseNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl