spring:
  profiles:
    active: dev
  application:
    name: saga-ticket-participant
  kafka:
    bootstrap-servers: http://mydev-db-mytest-kafka.mydev-db:9092


server:
  port: 8080

logging:
  level:
    web: INFO
    root: INFO
    cnadata: INFO

logging.config: file:/config/logback.xml

spring.main.allow-bean-definition-overriding: true


--- #dev 환경
spring:
  profiles: dev
  datasource:
    url: jdbc:mariadb://a77af7a1caaaf4d84a206b39779ef098-c3ca47260c19debc.elb.ap-northeast-2.amazonaws.com/test?allowMultiQueries=true
    username: admin
    password: ywyi1004
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
      #ddl-auto: create
      #ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        #physical-strategy: cnadata.outbox.util.DBLowerCaseNamingStrategy
        #physical-strategy: cnadata.outbox.util.DBUpperCaseNamingStrategy
  data:
    mongodb:
      host: a63573d6e6aa5479a9e65536e827e174-823303d80e2c5621.elb.ap-northeast-2.amazonaws.com
      username: root
      password: ywyi1004
      authentication-database: admin
      database: mydev-db
      port: 27017
